<a href="https://colab.research.google.com/github/JavZon/Working_with_files2/blob/main/Between_in_like_SQLite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
import numpy as np
import sqlite3 as sql

In [11]:
!wget https://github.com/anvarnarz/praktikum_datasets/raw/main/electricity.db

--2024-03-10 01:14:08--  https://github.com/anvarnarz/praktikum_datasets/raw/main/electricity.db
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/electricity.db [following]
--2024-03-10 01:14:09--  https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/electricity.db
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 565248 (552K) [application/octet-stream]
Saving to: ‘electricity.db.1’

electricity.db.1    100%[===================>] 552.00K  --.-KB/s    in 0.005s

2024-03-10 01:14:09 (110 MB/s) - ‘electricity.db.1’ saved [565248/565248]

In [33]:
db=sql.connect('electricity.db.1')
cursor=db.cursor()

In [34]:
query="SELECT name FROM sqlite_master WHERE type='table';"
cursor.execute(query)
cursor.fetchall()

[('elect',)]

In [35]:
query="PRAGMA table_info(elect);"
cursor.execute(query)
cursor.fetchall()

[(0, 'index', 'INTEGER', 0, None, 0),
 (1, 'country', 'TEXT', 0, None, 0),
 (2, 'code', 'TEXT', 0, None, 0),
 (3, 'year', 'INTEGER', 0, None, 0),
 (4, 'coal', 'REAL', 0, None, 0),
 (5, 'gas', 'REAL', 0, None, 0),
 (6, 'hydro', 'REAL', 0, None, 0),
 (7, 'renewable_other', 'REAL', 0, None, 0),
 (8, 'solar', 'REAL', 0, None, 0),
 (9, 'oil', 'REAL', 0, None, 0),
 (10, 'wind', 'REAL', 0, None, 0),
 (11, 'nuclear', 'REAL', 0, None, 0)]

In [23]:
query="SELECT country,year,coal,gas,hydro,oil FROM elect WHERE country='Uzbekistan' AND year BETWEEN 2005 and 2015"

In [31]:
df=pd.read_sql(query, db)
df[(df['year']==2005) | (df['year']==2010) | (df['year']==2015)]

       country  year       coal        gas  hydro       oil
0   Uzbekistan  2005  11.490919  25.278199  8.838  1.366882
5   Uzbekistan  2010   9.792027  30.199200  8.110  1.164793
10  Uzbekistan  2015  10.519789  35.780629  6.998  1.251363

In [21]:
query="SELECT country,year,coal,gas,hydro,oil FROM elect WHERE country='Uzbekistan' AND year IN(2000,2005,2010,2015)"

In [22]:
pd.read_sql(query, db)

      country  year       coal        gas  hydro       oil
0  Uzbekistan  2000  11.602405  25.523451  5.817  1.380143
1  Uzbekistan  2005  11.490919  25.278199  8.838  1.366882
2  Uzbekistan  2010   9.792027  30.199200  8.110  1.164793
3  Uzbekistan  2015  10.519789  35.780629  6.998  1.251363

In [39]:
query="SELECT DISTINCT country,year,coal,gas,hydro,oil FROM elect WHERE year=2015"
pd.read_sql(query, db)

            country  year         coal          gas        hydro          oil
0       Afghanistan  2015     0.000000     0.144000     1.001000     0.000000
1            Africa  2015   246.835961   292.686212   119.856820    92.816685
2           Albania  2015     0.000000     0.000000     5.836050     0.000000
3           Algeria  2015     0.000000    64.461440     0.144000     0.000000
4    American Samoa  2015     0.000000     0.000000     0.000000     0.163000
..              ...   ...          ...          ...          ...          ...
230  Western Sahara  2015     0.000000     0.000000     0.000000     0.000000
231           World  2015  8805.062857  5316.751699  3864.431708  1189.517813
232           Yemen  2015     0.000000     2.222898     0.000000     3.584422
233          Zambia  2015     0.000000     0.000000    12.907000     0.379760
234        Zimbabwe  2015     4.311780     0.000000     4.940000     0.000000

[235 rows x 6 columns]

In [44]:
query="""
SELECT country,year,coal,gas,hydro,oil
FROM elect
WHERE country LIKE 'N%' AND year IN (2010,2015);"""
pd.read_sql(query, db)

,country,year,coal,gas,hydro,oil
0,Namibia,2010,0.036367,0.000000,1.235000,0.018153
1,Namibia,2015,0.021319,0.000000,1.487000,0.010641
2,Nauru,2010,0.000000,0.000000,0.000000,0.023000
3,Nauru,2015,0.000000,0.000000,0.000000,0.024000
4,Nepal,2010,0.000000,0.000000,3.173000,0.002820
5,Nepal,2015,0.000000,0.000000,3.418000,0.000000
6,Netherlands,2010,22.588000,75.333000,0.105000,6.028615
7,Netherlands,2015,39.374902,47.272902,0.092699,5.820232
8,Netherlands Antilles,2010,0.000000,0.000000,0.000000,1.184400
9,Netherlands Antilles,2015,0.000000,0.000000,0.000000,0.692780
10,New Caledonia,2010,0.000000,0.000000,0.262000,1.703000
11,New Caledonia,2015,0.000000,0.000000,0.340406,2.345000
12,New Zealand,2010,5.586792,5.665008,24.479000,0.000000
13,New Zealand,2015,3.541988,3.591576,24.285000,1.098016
14,Nicaragua,2010,0.000000,0.298633,0.499000,1.868067
15,Nicaragua,2015,0.000000,0.296172,0.292000,1.852668
16,Niger,2010,0.063981,0.000000,0.000000,0.208619
17,Niger,2015,0.116269,0.000000,0.000000,0.379111
18,Nigeria,2010,0.000000,18.562180,6.310000,0.000000
19,Nigeria,2015,0.000000,25.095180,5.663790,0.000000
20,Niue,2010,0.000000,0.000000,0.000000,0.003000
21,Niue,2015,0.000000,0.000000,0.000000,0.003000
22,North America,2010,2114.916103,1257.092975,645.817477,90.510538
23,North America,2015,1564.177426,1688.612039,659.537925,66.647054
24,North Korea,2010,7.768160,0.000000,13.266000,0.000000
25,North Korea,2015,3.512780,0.000000,9.900000,0.000000
26,North Macedonia,2010,NaN,NaN,2.431000,NaN
27,North Macedonia,2015,NaN,NaN,1.865193,NaN
28,Norway,2010,0.000000,4.729140,116.257000,0.000000
29,Norway,2015,0.000000,2.606620,136.662000,0.000000